FROM python:3.12


WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y gcc g++ libc-dev

# Ensure required directories
RUN mkdir -p /app/vectorstore /app/raw_documents

COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.txt

# Copy everything
COPY . .

# Run the FastAPI server
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
